# Generated by Django 4.1.3 on 2022-11-28 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=100)),
                ('school', models.CharField(max_length=100)),
                ('collage', models.CharField(max_length=100)),
                ('degree', models.CharField(max_length=100)),
                ('uni_versity', models.CharField(blank=True, max_length=100)),
                ('skill', models.TextField(max_length=500)),
                ('work_exprince', models.TextField(max_length=500)),
                ('about_you', models.TextField(max_length=1000)),
            ],
        ),
    ]
